apiVersion: v1
kind: ServiceAccount
metadata:
  name: delete-failed-job
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: delete-failed-job-view
subjects:
  - kind: Group
    name: default-view
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: delete-failed-job
    namespace: default
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "delete-failed-job"
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: "delete-failed-job"
        image: "brunopadz/delete-failed-pods:latest"
        imagePullPolicy: Always
      restartPolicy: Never
      serviceAccountName: delete-failed-job
  backoffLimit: 2
